import {
    cibCcAmex,
    cibCcApplePay,
    cibCcMastercard,
    cibCcPaypal,
    cibCcStripe,
    cibCcVisa,
    cibFacebook,
    cibGoogle,
    cibLinkedin,
    cibSkype,
    cibTwitter,
    cibTravisci,
    cifBr,
    cifEs,
    cifFr,
    cifIn,
    cifPl,
    cifUs,
    cilLockUnlocked,
    cilAccountLogout,
    cilAlignCenter,
    cilAlignLeft,
    cilAlignRight,
    cilApplicationsSettings,
    cilArrowBottom,
    cilArrowRight,
    cilArrowTop,
    cilCog,
    cilHelp,
    cilLightbulb,
    cilMinus,
    cilBasket,
    cilBell,
    cilBold,
    cilBook,
    cilBookmark,
    cilBrush,
    cilBuilding,
    cilCalculator,
    cilCalendar,
    cilChart,
    cilChartPie,
    cilCheck,
    cilChevronLeft,
    cilChevronRight,
    cilCloud,
    cilCloudDownload,
    cilCode,
    cilContrast,
    cilCreditCard,
    cilCursor,
    cilDescription,
    cilDevices,
    cilDollar,
    cilDrop,
    cilEnvelopeClosed,
    cilEnvelopeOpen,
    cilFile,
    cilGrid,
    cilGlobeAlt,
    cilHome,
    cilInbox,
    cilIndentDecrease,
    cilIndentIncrease,
    cilItalic,
    cilJustifyCenter,
    cilLanguage,
    cilLayers,
    cilList,
    cilListNumbered,
    cilLocationPin,
    cilLockLocked,
    cilMagnifyingGlass,
    cilMap,
    cilMediaPlay,
    cilMediaRecord,
    cilMenu,
    cilMoon,
    cilNotes,
    cilOptions,
    cilPaperclip,
    cilPaperPlane,
    cilPen,
    cilPencil,
    cilPeople,
    cilPrint,
    cilPuzzle,
    cilReload,
    cilReportSlash,
    cilRouter,
    cilSave,
    cilSend,
    cilSettings,
    cilShare,
    cilShareAll,
    cilShareBoxed,
    cilSpeech,
    cilSpeedometer,
    cilSpreadsheet,
    cilStar,
    cilSun,
    cilTags,
    cilTask,
    cilTrash,
    cilTruck,
    cilUnderline,
    cilUser,
    cilUserFemale,
    cilUserFollow,
    cilUserUnfollow,
    cilZoom
  } from '@coreui/icons';
  
  export const iconSubset = {
    cibCcAmex,
    cibCcApplePay,
    cibCcMastercard,
    cibCcPaypal,
    cibCcStripe,
    cibCcVisa,
    cibFacebook,
    cibGoogle,
    cibLinkedin,
    cibSkype,
    cibTwitter,
    cibTravisci,
    cifBr,
    cifEs,
    cifFr,
    cifIn,
    cifPl,
    cifUs,
    cilAccountLogout,
    cilAlignCenter,
    cilAlignLeft,
    cilAlignRight,
    cilApplicationsSettings,
    cilArrowBottom,
    cilArrowRight,
    cilArrowTop,
    cilBasket,
    cilCog,
    cilHelp,
    cilLightbulb,
    cilMinus,
    cilBell,
    cilBold,
    cilBook,
    cilBookmark,
    cilBrush,
    cilBuilding,
    cilCalculator,
    cilCalendar,
    cilChart,
    cilChartPie,
    cilCheck,
    cilChevronLeft,
    cilChevronRight,
    cilCloud,
    cilCloudDownload,
    cilCode,
    cilContrast,
    cilCreditCard,
    cilCursor,
    cilDescription,
    cilDevices,
    cilDollar,
    cilDrop,
    cilEnvelopeClosed,
    cilEnvelopeOpen,
    cilFile,
    cilGrid,
    cilGlobeAlt,
    cilHome,
    cilInbox,
    cilIndentDecrease,
    cilIndentIncrease,
    cilItalic,
    cilJustifyCenter,
    cilLanguage,
    cilLayers,
    cilList,
    cilListNumbered,
    cilLocationPin,
    cilLockLocked,
    cilMagnifyingGlass,
    cilMap,
    cilMediaPlay,
    cilMediaRecord,
    cilMenu,
    cilMoon,
    cilNotes,
    cilOptions,
    cilPaperclip,
    cilPaperPlane,
    cilPen,
    cilPencil,
    cilPeople,
    cilPrint,
    cilPuzzle,
    cilReload,
    cilReportSlash,
    cilSettings,
    cilRouter,
    cilSave,
    cilSend,
    cilShare,
    cilShareAll,
    cilShareBoxed,
    cilSpeech,
    cilSpeedometer,
    cilSpreadsheet,
    cilStar,
    cilSun,
    cilTags,
    cilTask,
    cilTrash,
    cilTruck,
    cilUnderline,
    cilUser,
    cilUserFemale,
    cilUserFollow,
    cilUserUnfollow,
    cilZoom,
  };
  
  export enum IconSubset {
    cibCcAmex = 'cibCcAmex',
    cibCcApplePay = 'cibCcApplePay',
    cibCcMastercard = 'cibCcMastercard',
    cibCcPaypal = 'cibCcPaypal',
    cibCcStripe = 'cibCcStripe',
    cibCcVisa = 'cibCcVisa',
    cibFacebook = 'cibFacebook',
    cibGoogle = 'cibGoogle',
    cibLinkedin = 'cibLinkedin',
    cibSkype = 'cibSkype',
    cibTwitter = 'cibTwitter',
    cibTravisci = 'cibTravisci',
    cifBr = 'cifBr',
    cifEs = 'cifEs',
    cifFr = 'cifFr',
    cifIn = 'cifIn',
    cifPl = 'cifPl',
    cifUs = 'cifUs',
    cilAccountLogout = 'cilAccountLogout',
    cilAlignCenter = 'cilAlignCenter',
    cilAlignLeft = 'cilAlignLeft',
    cilAlignRight = 'cilAlignRight',
    cilApplicationsSettings = 'cilApplicationsSettings',
    cilArrowBottom = 'cilArrowBottom',
    cilArrowRight = 'cilArrowRight',
    cilArrowTop = 'cilArrowTop',
    cilBasket = 'cilBasket',
    cilCog = 'cilCog',
    cilHelp = 'cilHelp',
    cilLightbulb = 'cilLightbulb',
    cilMinus = 'cilMinus',
    cilBell = 'cilBell',
    cilBold = 'cilBold',
    cilBook = 'cilBook',
    cilBookmark = 'cilBookmark',
    cilBrush = 'cilBrush',
    cilBuilding = 'cilBuilding',
    cilCalculator = 'cilCalculator',
    cilCalendar = 'cilCalendar',
    cilChart = 'cilChart',
    cilChartPie = 'cilChartPie',

    cilCheck = 'cilCheck',
    cilChevronLeft = 'cilChevronLeft',
    cilChevronRight = 'cilChevronRight',
    cilCloud = 'cilCloud',
    cilCloudDownload = 'cilCloudDownload',
    cilCode = 'cilCode',
    cilContrast = 'cilContrast',
    cilCreditCard = 'cilCreditCard',
    cilCursor = 'cilCursor',
    cilDescription = 'cilDescription',
    cilDevices = 'cilDevices',
    cilDollar = 'cilDollar',
    cilDrop = 'cilDrop',
    cilEnvelopeClosed = 'cilEnvelopeClosed',
    cilEnvelopeOpen = 'cilEnvelopeOpen',
    cilFile = 'cilFile',
    cilGrid = 'cilGrid',
    cilGlobeAlt = 'cilGlobeAlt',
    cilHome = 'cilHome',
    cilInbox = 'cilInbox',
    cilIndentDecrease = 'cilIndentDecrease',
    cilIndentIncrease = 'cilIndentIncrease',
    cilItalic = 'cilItalic',
    cilJustifyCenter = 'cilJustifyCenter',
    cilLanguage = 'cilLanguage',
    cilLayers = 'cilLayers',
    cilList = 'cilList',
    cilListNumbered = 'cilListNumbered',
    cilLocationPin = 'cilLocationPin',
    cilLockLocked = 'cilLockLocked',
    cilMagnifyingGlass = 'cilMagnifyingGlass',
    cilMap = 'cilMap',
    cilMediaPlay = 'cilMediaPlay',
    cilMediaRecord = 'cilMediaRecord',
    cilMenu = 'cilMenu',
    cilMoon = 'cilMoon',
    cilNotes = 'cilNotes',
    cilOptions = 'cilOptions',
    cilPaperclip = 'cilPaperclip',
    cilPaperPlane = 'cilPaperPlane',
    cilPen = 'cilPen',
    cilPencil = 'cilPencil',
    cilPeople = 'cilPeople',
    cilPrint = 'cilPrint',
    cilPuzzle = 'cilPuzzle',
    cilReload = 'cilReload',
    cilReportSlash = 'cilReportSlash',
    cilSettings = 'cilSettings',
    cilRouter = 'cilRouter',
    cilSave = 'cilSave',
    cilSend = 'cilSend',
    cilShare = 'cilShare',
    cilShareAll = 'cilShareAll',
    cilShareBoxed = 'cilShareBoxed',
    cilSpeech = 'cilSpeech',
    cilSpeedometer = 'cilSpeedometer',
    cilSpreadsheet = 'cilSpreadsheet',
    cilStar = 'cilStar',
    cilSun = 'cilSun',
    cilTags = 'cilTags',
    cilTask = 'cilTask',
    cilTrash = 'cilTrash',
    cilTruck = 'cilTruck',
    cilUnderline = 'cilUnderline',
    cilUser = 'cilUser',
    cilUserFemale = 'cilUserFemale',
    cilUserFollow = 'cilUserFollow',
    cilUserUnfollow = 'cilUserUnfollow',
    cilZoom = 'cilZoom',
    logo = 'logo',
    signet = 'signet'
  }
  
  